import { Trope } from '@/types/trope';

// Create and download a text file
const downloadTextFile = (content: string, filename: string): void => {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.style.display = 'none';
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  // Clean up the URL object
  setTimeout(() => URL.revokeObjectURL(url), 1000);
};

export const exportTropesToText = (tropes: Trope[]): void => {
  if (tropes.length === 0) {
    console.warn('No tropes to export');
    return;
  }

  let content = 'D&D STORY TROPES\n';
  content += '================\n\n';
  content += `Generated: ${new Date().toLocaleString()}\n`;
  content += `Total Tropes: ${tropes.length}\n\n`;

  tropes.forEach((trope, index) => {
    content += `${index + 1}. ${trope.name}\n`;
    content += `${'='.repeat(trope.name.length + 3)}\n`;
    content += `${trope.detail}\n\n`;
  });

  content += '\n---\n';
  content += 'Generated by D&D Story Copilot\n';

  downloadTextFile(content, 'dnd-tropes.txt');
};

export const exportDnDCampaignTemplate = (tropes: Trope[]): void => {
  if (tropes.length === 0) {
    console.warn('No tropes to export');
    return;
  }

  const template = `D&D FANTASY ADVENTURE TEMPLATE USING STORY TROPES
==================================================

INSTRUCTIONS:
Insert 1–6 tropes from TVTropes.org or similar into the section below. Then follow the prompts to build your campaign structure.

TROPES SELECTED:
${tropes.map((trope, index) => `- ${trope.name}`).join('\n')}

--------------------------------------------------

CAMPAIGN TITLE AND PREMISE
--------------------------
[Insert a compelling fantasy campaign title]

Summary:
[1–2 paragraph summary. Show how the selected tropes intersect to shape the world and conflict.]

--------------------------------------------------

ADVENTURE HOOKS
---------------
[List 3–5 quest hooks that draw the players into the campaign. Each should reflect the tone and theme of the selected tropes.]

1.
2.
3.
4.
5.

--------------------------------------------------

KEY LOCATIONS
-------------
[Describe at least 3 major locations. For each, include a name, description, significance, and any magical/supernatural effects.]

- Location 1:
  Description:
  Importance:
  Unusual Effects/Inhabitants:

- Location 2:
  Description:
  Importance:
  Unusual Effects/Inhabitants:

- Location 3:
  Description:
  Importance:
  Unusual Effects/Inhabitants:

--------------------------------------------------

IMPORTANT NPCs
--------------
[Describe 3–5 memorable NPCs. Include name, role, personal agenda, what they want from the PCs, and roleplaying tips.]

- NPC 1:
  Role:
  Agenda:
  Wants:
  RP Tips:

- NPC 2:
  Role:
  Agenda:
  Wants:
  RP Tips:

- NPC 3:
  Role:
  Agenda:
  Wants:
  RP Tips:

--------------------------------------------------

SITUATIONAL STRUCTURE
----------------------
[List 4–6 key situations the players might face. These are not in strict order but are major non-linear challenges.]

- Situation 1: [Short Title]
  Setup:
  Choices/Conflict:
  Linked Tropes:

- Situation 2: [Short Title]
  Setup:
  Choices/Conflict:
  Linked Tropes:

- Situation 3: [Short Title]
  Setup:
  Choices/Conflict:
  Linked Tropes:

- Situation 4: [Short Title]
  Setup:
  Choices/Conflict:
  Linked Tropes:

--------------------------------------------------

RECURRING THEMES
----------------
[List 2–3 overarching themes or philosophical ideas that emerge from the tropes selected.]

1.
2.
3.

--------------------------------------------------

OPTIONAL ADD-ONS
----------------
Would you like to generate:
- Midjourney prompts for any NPC or location?
- A player-facing handout or summary?
- Mechanical elements like sanity rolls, corruption, magical effects, or custom monsters?

---
Generated by D&D Story Copilot
${new Date().toLocaleString()}
`;

  downloadTextFile(template, 'dnd-campaign-template.txt');
};