name: Deploy SPA to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Add your build steps here (example shows npm for Node-based SPA)
      - name: Install dependencies
        run: npm ci

      - name: Build SPA
        run: npm run build  # Adjust if your build command is different

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist  # Your build output directory (e.g., 'dist' or 'build')

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
